server:
   port: 8080

logging:
    path: logs
    file: mylog.log


spring:
   application:
          name: report
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/oa
       username: root
       password: root

mybatis:
    type-aliases-package: com.course.model
    mapper-locations:
       - mapper/*
